language: android
jdk: oraclejdk7

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   # via the "travis encrypt" command using the project repo's public key
   - secure: "SGSNk6CwuNjp5yVHKB95GxjhlYmph86BUeFPwl7IYnqe5WoUR9sXkOYSuMLO5qEXr+e2YaYVIZp70xI/jBi+r/kTEdWUYjtchs/kz7dDCXLISJCpUnAIxgVNx/V3ez4/jwWI89MJcLsgJGARAziio8fBgbJf7m+grD4KIu8Ogxg="
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

addons:
  coverity_scan:
    project:
      name: "OleksandrKucherenko/meter"
      description: "Micro-benchmarking tool for Android projects."
    build_command_prepend: "./gradlew clean --info --no-color"
    build_command:   "./gradlew assembleDebug --info --no-color"
    branch_pattern: coverity_scan


before_install:
  - android list sdk --no-ui --all --extended | grep -E '^id:' | awk -F '"' '{$1=""; print $2}'
#  - echo yes | android update sdk --all --filter build-tools-19.1.0 --no-ui --force

# list of available components https://github.com/travis-ci/travis-ci/issues/2301
android:
  components:
    - platform-tools
    - build-tools-19.1.0
    - build-tools-20.0.0
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - android-19
  licenses:
    - '.+'

before_script:
    - chmod +x gradlew
    # Create and start emulator
    #- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    #- emulator -avd test -no-skin -no-audio -no-window &
    #- adb wait-for-device
    #- adb shell input keyevent 82 &

script:
    - ./gradlew test --info --no-color
    # - ./gradlew connectedAndroidTest --no-color
